import Head from "next/head";
import Brand from "../components/Brand";
import CardEvent from "../components/CardEvent";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Statistic from "../components/Statistic";
import Story from "../components/Story";
import { getData } from "../utils/fetchData";

export default function Home({ data }) {
    return (
        <>
            <Head>
                <title>Semina || Landing Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Brand />
            <CardEvent
                data={data}
                title="Featured Events"
                subTitle="Grow Today"
            />
            <Story />
            <Statistic />
            <Footer />
        </>
    );
}

export async function getServerSideProps(context) {
    const req = await getData("/events");
    const res = req.data;

    return {
        props: { data: res },
    };
}
